version: '3.7'
services:
    app:
        network_mode: bridge
        container_name: exercicios-react
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - '3001:3000'
        environment:
            - NODE_ENV=development