
version: '3'

services:
  server:
    network_mode: bridge
    container_name: express
    build: '.'
    volumes:
      - ./:/node-app
    environment:
      NODE_ENV: development
    depends_on:
      - db
    links:
      - db
    ports:
      - '3003:3000'

  db:
    network_mode: bridge
    image: 'mongo'
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db