version: '3'

services:

  frontend:
    container_name: reactapp
    network_mode: bridge
    build: './frontend'
    volumes:
      - './frontend:/app'
      - 'app/node_modules'
    ports:
      - 8080:8080
    environment:
      NODE_ENV: development
    depends_on: 
      - server1
      - server2
   
  server1:
    network_mode: bridge
    container_name: expressapp
    build: './backend'
    volumes:
      - ./backend:/node-app
    environment:
      NODE_ENV: development
    depends_on:
      - db
    links:
      - db
    ports:
      - '5001:5000'

  server2:
    network_mode: bridge
    container_name: expressapp2
    build: './backend'
    volumes:
      - ./backend:/node-app
    environment:
      NODE_ENV: development
    depends_on:
      - db
    links:
      - db
    ports:
      - '5002:5000'

  loadbalancer:
    network_mode: bridge
    container_name: loadbalancer
    build: '.'
    links:
        - server1
        - server2
    ports:
        - '5000:80'

  db:
    network_mode: bridge
    image: 'mongo'
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./backend/data/db:/data/db
    restart: unless-stopped

  