version: '3'

services:

  frontend:
    container_name: reactapp
    network_mode: bridge
    build: './frontend'
    volumes:
      - './frontend:/app'
      - 'app/node_modules'
    ports:
      - 8080:8080
    environment:
      NODE_ENV: development
    depends_on: 
      - server
   
  server:
    network_mode: bridge
    container_name: expressapp
    build: './backend'
    volumes:
      - ./backend:/node-app
    environment:
      NODE_ENV: development
    depends_on:
      - db
    links:
      - db
    ports:
      - '3004:3004'

  db:
    network_mode: bridge
    image: 'mongo'
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./backend/data/db:/data/db
    restart: unless-stopped